name: Push secret

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags to push'
        required: true
        default: 'latest'

# Do we need permissions?
permissions:
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # password: ${{ secrets.GH_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/push-secret-image:${{ inputs.tags }}
            ghcr.io/${{ github.repository_owner }}/push-secret-image:latest